#!/usr/bin/env python3
"""The suites themselves, checked the way they check the product.

Two failures made this file necessary, and both had the same shape: a suite
that was not running, reporting a number that looked like it was.

  * Every suite redirects HOME to a scratch directory so a test never touches
    the machine it runs on. On Windows `Path.home()` does not read HOME at all
    -- it reads USERPROFILE -- so those suites silently tested the REAL home.
    Found the honest way: `C:/Users/muali/.ssh/` contained agent_readonly and
    agent_write, generated by a test run days earlier.

  * `read_text()` with no encoding is cp1252 on Windows. The product writes
    UTF-8, so a suite reading its own fixture back crashed on a byte it had
    just written; run_all filed the crash as SKIP and the run stayed green.

Neither is a bug in the bot. Both are reasons a bug in the bot could ship
unnoticed, which is the same thing one step removed.
"""
import ast
import pathlib
import sys

DEV = pathlib.Path(__file__).resolve().parent

results: list[tuple[str, bool]] = []


def check(name: str, ok: bool) -> None:
    results.append((name, bool(ok)))
    print(("PASS - " if ok else "FAIL - ") + name)


suites = sorted(DEV.glob("test_*.py"))
check(f"there are suites to inspect ({len(suites)} found)", len(suites) > 20)

# --- 1. a scratch HOME has to be scratch on every OS ------------------------
offenders = []
for p in suites:
    text = p.read_text(encoding="utf-8")
    if 'os.environ["HOME"]' in text and "USERPROFILE" not in text:
        offenders.append(p.name)

check("every suite that redirects HOME also redirects USERPROFILE, or "
      f"Path.home() reads the real home on Windows ({len(offenders)} missing)",
      not offenders)
if offenders:
    print("       " + ", ".join(offenders))

# --- 2. text IO is never left to the platform default -----------------------
bare = []
for p in suites + [DEV / "run_all.py", DEV / "code_index.py",
                   DEV / "error_index.py"]:
    if not p.exists():
        continue
    for node in ast.walk(ast.parse(p.read_text(encoding="utf-8"))):
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr in ("read_text", "write_text")
                and not any(k.arg == "encoding" for k in node.keywords)):
            bare.append(f"{p.name}:{node.lineno}")

check("no read_text/write_text is left to the platform codec -- cp1252 "
      f"cannot read what the product wrote as UTF-8 ({len(bare)} bare)",
      not bare)
if bare:
    print("       " + ", ".join(bare[:8]))

# --- 3. a suite must actually report a tally --------------------------------
# run_all treats a missing tally as SKIP. A suite that never prints one is
# therefore invisible rather than failing, so the tally itself is guarded.
no_tally = [p.name for p in suites
            if "passed" not in p.read_text(encoding="utf-8")]
check(f"every suite prints a tally run_all can read ({len(no_tally)} silent)",
      not no_tally)
if no_tally:
    print("       " + ", ".join(no_tally))


# --- 4. the working copy agrees with .gitattributes -------------------------
# `* text=auto eol=lf`, so git stores LF whatever the checkout looks like. The
# trap is one level up: Path.write_text() on Windows turns every \n into \r\n
# unless newline="" is passed, so a patch script rewrites whole files as CRLF
# and every later diff, grep and shell script sees something the repository
# does not contain. Bytes, not text -- reading as text would hide it.
REPO = DEV.parent
crlf = []
for pattern in ("*.py", "dev/*.py", "tools/*.py", "systemd/*", ".githooks/*",
                "*.sh"):
    for f in sorted(REPO.glob(pattern)):
        if f.is_file() and "__pycache__" not in str(f):
            if b"\r\n" in f.read_bytes():
                crlf.append(f.name)

check("no tracked source file carries CRLF, which .gitattributes says this "
      f"repository does not contain ({len(crlf)} found)", not crlf)
if crlf:
    print("       " + ", ".join(crlf[:8]))

failed = [n for n, ok in results if not ok]
print(f"\n{len(results) - len(failed)}/{len(results)} passed")
if failed:
    print("FAILED:", failed)
    sys.exit(1)
